kinopoisk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns



urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('pages/', include('django.contrib.flatpages.urls')),
    path('contact/', include("contact.urls")),
    path('', include("movies.urls", namespace='movies')),
    path('', include("users.urls", namespace='users')),
    
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from .views import movies, movie_detail, add_review, actorview

from .import views

app_name = 'movies'



# urlpatterns = [
#     path('', views.MoviesView.as_view(), name='index'),
#     path('<slug:slug>', views.MovieDetailView.as_view(), name='movie_detail'),
    
# ]

urlpatterns = [
    path('', movies, name='index'),
    path("add-rating/", views.AddStarRating.as_view(), name='add_rating'),
    # path('filter/', get_queryset, name='filter'),
    path('<slug:slug>', movie_detail, name='movie_detail'),
    path('review/<int:pk>/', add_review, name="add_review"),
    path('actor/<str:slug>/',actorview, name='actorview'),
    
]

users/urls.py
from django.urls import path
from .views import register
from django.contrib.auth import views as auth_views
from users import views as user_views

app_name = 'users'


urlpatterns = [
    path('register/', register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

movies/models.py
from django.db import models
from datetime import date
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    # Категория
    name = models.CharField("Категория", max_length = 150)
    description = models.TextField("Описание")
    url = models.SlugField(max_length = 160, unique = True)

    def __str__(self) -> str:
        return self.name
    
    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "категория"

class Actor(models.Model):
    # Актеры и режиссеры
    name = models.CharField("Имя", max_length=100)
    age = models.PositiveSmallIntegerField("Возраст", default=0)
    description = models.TextField("Описание")
    image = models.ImageField("изображение", upload_to="actors/")

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = "Актеры и режиссеры"
        verbose_name_plural = "Актеры и режиссеры"

class Genre(models.Model):
    # Жанры
    name = models.CharField("Имя", max_length = 150)
    description = models.TextField("Описание")
    url = models.SlugField(max_length = 160, unique = True)

    def __str__(self) -> str:
        return self.name
    
    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"

class Movie(models.Model):
    # Фильмы
    title = models.CharField("Название", max_length = 100)
    tagline = models.CharField("Слоган", max_length=100, default='')
    description = models.TextField("Описание")
    poster = models.ImageField("Постер", upload_to="movies/")
    year = models.PositiveSmallIntegerField("Дата выхода", default=2019)
    country = models.CharField("Страна", max_length=30)
    directors = models.ManyToManyField(Actor, verbose_name="режиссер", related_name="film_director")
    actors = models.ManyToManyField(Actor, verbose_name="актеры", related_name="film_actor")
    genres = models.ManyToManyField(Genre, verbose_name="жанры")
    world_premier = models.DateField("Премьера в мире", default=date.today)
    budget = models.PositiveIntegerField("Бюджет", default=0, help_text="указывать сумму в долларах")
    fees_in_usa = models.PositiveIntegerField(
        "Сборы в США", default=0, help_text="указывать сумму в долларах"
    )

    fees_in_world = models.PositiveIntegerField(
        "Сборы в мире", default=0, help_text="указывать сумму в долларах"
    )

    category = models.ForeignKey(
        Category, verbose_name="Категория", on_delete=models.SET_NULL, null=True
    )
    url = models.SlugField(max_length=130, unique=True)
    draft = models.BooleanField("Черновик", default=False)

    def __str__(self) -> str:
        return self.title
    
    def get_review(self):
        return self.review_set.filter(parent__isnull=True)
    
    
    class Meta:
        verbose_name = "Фильм"
        verbose_name_plural = "Фильмы"

class MovieShots(models.Model):
    # Кадры из фильма
    title = models.CharField("Заголовок", max_length=100)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="movie_shots/")
    movie = models.ForeignKey(Movie, verbose_name='Фильм', on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.title
    
    class Meta:
        verbose_name = "Кадр из фильма"
        verbose_name_plural = "Кадры из фильма"

class RatingStar(models.Model):
    # Звезда рейтинга
    value = models.SmallIntegerField("Значение", default=0)

    def __str__(self) -> str:
        return f'{self.value}'

    class Meta:
        verbose_name = "Звезда рейтинга"
        verbose_name_plural = "Звезды рейтинга"
        ordering = ["-value"]

class Rating(models.Model):
    # Рейтинг
    ip = models.CharField("IP адрес", max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name="звезда")
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="фильм")

    def __str__(self) -> str:
        return f"{self.star} - {self.movie}"
    
    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"

class Review(models.Model):
    # Отзывы
    email = models.EmailField()
    name = models.CharField("Имя", max_length=100)
    text = models.TextField("Сообщение", max_length=5000)
    parent = models.ForeignKey(
        'self', verbose_name="Родитель", on_delete=models.SET_NULL, blank=True, null=True
    )
    movie = models.ForeignKey(Movie, verbose_name ="фильм", on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f'{self.name} - {self.movie}'
    
    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

movies/forms.py
from django import forms
from snowpenguin.django.recaptcha3.fields import ReCaptchaField
from .models import Review, Rating, RatingStar

class ReviewForm(forms.ModelForm):
    # Форма отзывов
    captcha = ReCaptchaField()
    class Meta:
        model = Review
        fields = ("name", "email", "text", "captcha")
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control border"}),
            "email": forms.EmailInput(attrs={"class": "form-control border"}),
            "text": forms.Textarea(attrs={"class": "form-control border", "id": "contactcomment"})
        }


class RatingForm(forms.ModelForm):
    """Форма добавления рейтинга"""
    star = forms.ModelChoiceField(
        queryset=RatingStar.objects.all(), widget=forms.RadioSelect(), empty_label=None
    )

    class Meta:
        model = Rating
        fields = ("star",)

movies/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.http import HttpResponseServerError
from django.http import JsonResponse, HttpResponse

# Create your views here.
from .models import Movie, Actor, Genre, Rating
from django.shortcuts import get_object_or_404
from .forms import ReviewForm, RatingForm

# class MoviesView(View):
#     # "Список фильмов"
#     def get(self, request):
#         movies = Movie.objects.all()
#         return render(request, "movies/movies.html", {"movies": movies})
    
# class MovieDetailView(View):
#     def get(self, request, slug):
#         movie = Movie.objects.get(url=slug)
#         return render(request, "movies/moviesingle.html", {"movie": movie})
    
# def get_categories():
#     categories = Category.objects.all()
#     return categories

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.http import QueryDict

def movies(request):
    all_movies = Movie.objects.filter(draft=False)
    genres = Genre.objects.all()
    years = all_movies.values("year").distinct()

    # Получаем параметры из URL
    selected_years = request.GET.getlist('year')
    selected_genres = request.GET.getlist('genre')
    search_query = request.GET.get('search')

    # Применяем фильтры
    if search_query:
        movies = all_movies.filter(title__icontains=search_query)
    elif selected_years and selected_genres:
        movies = all_movies.filter(year__in=selected_years, genres__in=selected_genres).distinct()
    elif selected_years:
        movies = all_movies.filter(year__in=selected_years)
    elif selected_genres:
        movies = all_movies.filter(genres__in=selected_genres).distinct()
    else:
        movies = all_movies

    paginator = Paginator(movies, 3)
    page = request.GET.get('page')

    try:
        movies = paginator.page(page)
    except PageNotAnInteger:
        movies = paginator.page(1)
    except EmptyPage:
        movies = paginator.page(paginator.num_pages)
    
    # Создаем новый QueryDict для сохранения текущего состояния параметров
    query_params = QueryDict(mutable=True)
    query_params.setlist('year', selected_years)
    query_params.setlist('genre', selected_genres)
    if search_query:
        query_params['search'] = search_query
    
    context = {
        'movies': movies,
        'genres': genres,
        'years': years,
        'selected_years': selected_years,
        'selected_genres': selected_genres,
        'search_query': search_query,
        'query_params': query_params.urlencode(),  # Передаем параметры обратно в шаблон
    }
    return render(request, 'movies/movies.html', context)



def movie_detail(request, slug):
    # Полное описание фильма
    movie = get_object_or_404(Movie, url=slug)
    
    try:
        # Пытаемся получить рейтинг фильма, если он есть
        rating = Rating.objects.get(movie_id=movie)
    except Rating.DoesNotExist:
        # Если рейтинг не найден, устанавливаем его в None
        rating = None

     # Получаем доступные года и жанры
    all_movies = Movie.objects.filter(draft=False)
    genres = Genre.objects.all()
    years = all_movies.values("year").distinct()
    
    # Создаем экземпляр формы
    star_form = RatingForm()
    form = ReviewForm()

    # Добавляем форму в контекст
    context = {
        'movie': movie,
        'star_form': star_form,
        'rating': rating,
        'form': form,
        'genres': genres,
        'years': years,
    }
    return render(request, 'movies/moviesingle.html', context)


def add_review(request, pk):
    # Отзывы
    form = ReviewForm(request.POST)
    movie = Movie.objects.get(id=pk)
    if form.is_valid():
        form = form.save(commit=False)
        if request.POST.get("parent", None):
            form.parent_id = int(request.POST.get("parent"))
        form.movie = movie
        form.save()
        return redirect('movies:movie_detail', slug=movie.url)
    return render(request, 'movies/add_review.html', {'form': form, 'movie': movie})


def actorview(request, slug):
    # Инфо о актере или режисере
    actor = Actor.objects.get(name=slug)
    context = {
        'actor': actor,
    }
    return render(request, 'movies/actor.html', context)

def Search(request):
    paginate_by = 3




class AddStarRating(View):
    """Добавление рейтинга фильму"""
    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    def post(self, request):
        form = RatingForm(request.POST)
        if form.is_valid():
            Rating.objects.update_or_create(
                ip=self.get_client_ip(request),
                movie_id=int(request.POST.get("movie")),
                defaults={'star_id': int(request.POST.get("star"))}
            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)
    

    
# def get_queryset(request):
#     try:
#         years = request.GET.getlist("year")
#         queryset = Movie.objects.filter(year__in=years)
#         return queryset
#     except Exception as e:
#         return HttpResponseServerError(f"An error occurred: {e}")

# def get_queryset(request):
#     try:
#         years = [int(year) for year in request.GET.getlist("year")]
#         queryset = Movie.objects.filter(year__in=years)
#         return queryset
#     except Exception as e:
#         return HttpResponseServerError(f"An error occurred: {e}")

templates/movies/actor.html
{% extends "movies/base.html" %}
{% load static %}
{% block title %} {{ actor.title}}  {% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}


{% block movie %}
                <div class="left-ads-display col-lg-8">
                    <div class="row">
                        <div class="desc1-left col-md-6">
                            <img src="{{ actor.image.url }}" class="img-fluid" alt="">
                        </div>
                        <div class="desc1-right col-md-6 pl-lg-4">
                            <h3 class="editContent" style="outline: none; cursor: inherit;">
                                {{movie.title}}</h3>
                            <h5 class="editContent"></h5>
                            <ul>
                                <li><span><b>Возраст:</b> {{ actor.age }} лет</span></li>                  

                                <li>
                                    <span><b>Режиссер:</b>
                                        {% for movie in actor.film_director.all %}
                                            {{ movie.title }}
                                        {% endfor %}
                                    </span>
                                </li>
                                <li style="list-style: none"><span><b>Актер:</b> 
                                    {% for movie in actor.film_actor.all %}
                                        {{ movie.title }}
                                    {% endfor %}
                                    </span>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="row sub-para-w3layouts mt-5">
                        <h3 class="shop-sing editContent">
                            О {{ actor.name }}
                        </h3>
                        <p class="editContent">
                            {{ actor.description|safe }}
                        </p>
                    </div>
                        
                </div>
            
{% endblock movie %}

templates/movies/base.html
{% extends 'base.html' %} 
{% block title %} {% endblock title %}
{% block content %}
<section class="ab-info-main py-md-5 py-4 editContent" style="padding-left: 3rem; padding-right: 3rem;">
    {% block container %}
        <div class="container-fluid py-md-3">
    {% endblock container %}
        <div class="row">
            {% block sidebar %}
                <div class="side-bar col-lg-3">
            {% endblock sidebar %}
            {% include 'include/sidebar.html' %}
            </div>
            {% block movie %}
            {% endblock movie %}
            
        </div>
    </div>
</section>  
{% endblock content %}

templates/movies/movies.html
{% extends 'movies/base.html' %}
{% block title %} {% endblock title %}
{% block header %} bg1 {% endblock header %}
{% block movie %}
  <div class="left-ads-display col-lg-9">
    <div class="row">
      {% for movie in movies %}
        <div class="col-md-4 product-men">
          <div class="product-shoe-info editContent text-center mt-lg-4">
            <div class="men-thumb-item">
              <img src="{{ movie.poster.url }}" class="img-fluid" alt="" />
            </div>
            <div class="item-info-product">
              <h4 class=""><a href="{% url 'movies:movie_detail' movie.url %}" class="editContent">{{ movie.title }}</a></h4>

              <div class="product_price">
                <div class="grid-price">
                  <span class="money editContent">{{ movie.tagline }}</span>
                </div>
              </div>
              <ul class="stars">
                <li>
                  <a href="#"><span class="fa fa-star" aria-hidden="true"></span></a>
                </li>
                <li>
                  <a href="#"><span class="fa fa-star" aria-hidden="true"></span></a>
                </li>
                <li>
                  <a href="#"><span class="fa fa-star-half-o" aria-hidden="true"></span></a>
                </li>
                <li>
                  <a href="#"><span class="fa fa-star-half-o" aria-hidden="true"></span></a>
                </li>
                <li>
                  <a href="#"><span class="fa fa-star-o" aria-hidden="true"></span></a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
    {% include "include/pagination.html" %}
  </div>
{% endblock movie %}

templates/movies/moviesingle.html
{% extends 'movies/base.html' %}
{% load static i18n %}
{% block title %} {{ movie.title }} {% endblock title %}

    {% block container %}
        <div class="container py-md-3">
    {% endblock container %}
            {% block sidebar %}
                <div class="side-bar col-lg-4">
            {% endblock sidebar %}
{% block movie %}
                <div class="left-ads-display col-lg-8">
                    <div class="row">
                        <div class="desc1-left col-md-6">
                            <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
                        </div>
                        <div class="desc1-right col-md-6 pl-lg-4">
                            <h3 class="editContent" style="outline: none; cursor: inherit;">
                                {{movie.title}}</h3>
                            <h5 class="editContent"></h5>
                            <ul>
                                <li style="list-style: none"><span><b>{% trans 'Год' %}:</b> {{ movie.year }}</span></li>
                                <li style="list-style: none"><span><b>{% trans 'Страна' %}:</b> {{ movie.country }}</span></li>
                                <li style="list-style: none"><span><b>{% trans 'Слоган' %}:</b> {{ movie.tagline }}</span></li>
                                <li style="list-style: none">
                                    <span><b>{% trans 'Режиссер' %}:</b>
                                        {% for director in movie.directors.all %}
                                            <a href="{% url 'movies:actorview'  director.name %}">{{ director.name }} </a>
                                        {% endfor %}
                                    </span>
                                </li>
                                <li style="list-style: none"><span><b>{% trans 'Актеры' %}:</b> 
                                    {% for actor in movie.actors.all %}
                                        <a href="{% url 'movies:actorview'  actor.name %}">{{ actor.name }}</a>
                                    {% endfor %}
                                    </span>
                                </li>
                                <li style="list-style: none"><span><b>{% trans 'Жанр' %}:</b>
                                    {% for genre in movie.genres.all %}
                                        {{ genre.name }}
                                    {% endfor %}
                                    </span>
                                </li>
                                <li style="list-style: none"><span><b>{% trans 'Премьера в мире' %}:</b> {{ movie.world_premiere }}</span>
                                </li>
                                <li style="list-style: none">
                                    <span><b>{% trans 'Бюджет' %}:</b> ${{ movie.budget }}</span></li>
                                <li style="list-style: none">
                                    <span><b>{% trans 'Сборы в США' %}:</b> ${{ movie.fees_in_usa }}</span></li>
                                <li style="list-style: none"><span><b>{% trans 'Сборы в мире' %}:</b> ${{ movie.fess_in_world }}</span>
                                </li>
                                
                                <li>
                                   <form action="{% url 'movies:add_rating' %}" method="post" name="rating">
                                        <b>Рейтинг:</b>
                                        {% csrf_token %}
                                        <input type="hidden" value="{{ movie.id }}" name="movie">
                                        <span class="rating">
                                            {% for k, v in star_form.fields.star.choices %}
                                                <input id="rating{{ v }}" type="radio" name="star"
                                                    value="{{ k }}">
                                                <label for="rating{{ v }}">{{ k }}</label>
                                            {% endfor %}
                                        </span>
                                        <span class="editContent">{{ rating.star }}</span>
                                    </form>
                                </li>
                                <div class="share-desc">
                                    <div class="share">
                                        <h4 class="editContent"
                                            style="outline: none; cursor: inherit;">
                                            Share:</h4>
                                        <ul class="w3layouts_social_list list-unstyled">
                                            <li>
                                                <a href="#" class="w3pvt_facebook editContent"
                                                   style="outline: none; cursor: inherit;">
                                                <span class="fa fa-facebook-f"
                                                      style="outline: none; cursor: inherit;"></span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#" class="w3pvt_twitter editContent"
                                                   style="outline: none; cursor: inherit;">
                                                <span class="fa fa-twitter"
                                                      style="outline: none; cursor: inherit;"></span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#" class="w3pvt_dribble editContent"
                                                   style="outline: none; cursor: inherit;">
                                                <span class="fa fa-dribbble"
                                                      style="outline: none; cursor: inherit;"></span>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                        </div>
                    </div>
                    <div class="row sub-para-w3layouts mt-5">

                        <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                            О фильме {{ movie.title }}</h3>
                        <p>
                            {% for image in movie.movieshots_set.all %}
                            <img src="{{ image.image.url }}" class="img-movie-shots" alt="{{ image.description }}">
                            {% endfor %}
                        </p>
                        <p class="editContent" style="outline: none; cursor: inherit;">
                            {{ movie.description|safe }}
                            </p>
                        <!-- <p class="mt-3 italic-blue editContent"
                           style="outline: none; cursor: inherit;">
                            <iframe width="560" height="315"
                                    src="https://www.youtube.com/embed/A36LahZNUiE?controls=0"
                                    frameborder="0" allow="accelerometer; autoplay;
                                                                           encrypted-media; gyroscope; picture-in-picture"
                                    allowfullscreen>

                            </iframe>
                        </p> -->
                    </div>
                    <hr>
                    <div class="row">
                        <div class="single-form-left">
                            <!-- contact form grid -->
                            <div class="contact-single">
                                <h3 class="editContent">
                                    <span class="sub-tittle editContent">{{ movie.review_set.count }}</span>Оставить отзыв</h3>
                                <form action="{% url 'movies:add_review' movie.id %}" method="post" class="mt-4" id="formReview">
                                    {% csrf_token %}
                                    <input type="hidden" name="parent" id="contactparent" value="">
                                    <div class="form-group editContent">
                                        <label for="contactcomment" class="editContent"> Ваш комментарий *</label>
                                        {{ form.text }}
                                    </div>
                                    <div class="d-sm-flex">
                                        <div class="col-sm-6 form-group p-0 editContent">
                                            <label for="contactusername" class="editContent">Имя *</label>
                                            {{ form.name }}
                                        </div>
                                        <div class="col-sm-6 form-group ml-sm-3 editContent">
                                            <label for="contactemail" class="editContent"> Email *</label>
                                            {{ form.email }}
                                        </div>
                                        {{ form.captcha }}
                                    </div>
                                    <button type="submit" class="mt-3 btn btn-success btn-block py-3"> Отправить</button>
                                </form>
                            </div>
                            <!--  //contact form grid ends here -->
                        </div>
                    </div>
    
                        {% comment %} {% for revie in movie.review_set.all %} {% endcomment %}
                        {% for revie in movie.get_review %}
                            <div class="media py-5">
                                <img src="{% static 'images/te2.jpg'  %}" class="mr-3 img-fluid-us" alt="image">     
                                <div class="media-body mt-4">
                                    <h5 class="mt-0 editContent">
                                        {{ revie.name }}
                                    </h5>
                                    <p class="mt-2 editContent">
                                        {{ revie.text }}
                                        
                                    </p>

                                    <a href="#formReview" onclick="addReview('{{ revie.name }}', '{{ revie.id }}')">Ответить</a>
                                    
                                    {% for rew in revie.review_set.all %}
                                    <div class="media mt-5 editContent"
                                        style="outline: none; cursor: inherit;">
                                        <a class="pr-3" href="#">
                                            <img src="{% static 'images/te2.jpg' %}" class="img-fluid "
                                                alt="image" style="outline: none; cursor: inherit;">
                                        </a>
                                        <div class="media-body">
                                            <h5 class="mt-0 editContent"
                                                style="outline: none; cursor: inherit;">{{ rew.name }}</h5>
                                            <p class="mt-2 editContent"
                                            style="outline: none; cursor: inherit;"> {{ rew.text }}</p>
                                        </div>
                                    </div>
                                    {% endfor %}

                                </div>
                            </div>
                        {% endfor %}
                </div>
            </div>

            <script>
                function addReview(name, id){
                    document.getElementById("contactparent").value = id;
                    document.getElementById("contactcomment").innerText = `${name},`;
                }
            </script>
            
{% endblock movie %}