kinopoisk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns



urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('pages/', include('django.contrib.flatpages.urls')),
    path('contact/', include("contact.urls")),
    path('', include("movies.urls", namespace='movies')),
    path('', include("users.urls", namespace='users')),
    
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from .views import movies, movie_detail, add_review, actorview

from .import views

app_name = 'movies'



# urlpatterns = [
#     path('', views.MoviesView.as_view(), name='index'),
#     path('<slug:slug>', views.MovieDetailView.as_view(), name='movie_detail'),
    
# ]

urlpatterns = [
    path('', movies, name='index'),
    path("add-rating/", views.AddStarRating.as_view(), name='add_rating'),
    # path('filter/', get_queryset, name='filter'),
    path('<slug:slug>', movie_detail, name='movie_detail'),
    path('review/<int:pk>/', add_review, name="add_review"),
    path('actor/<str:slug>/',actorview, name='actorview'),
    
]

users/urls.py
from django.urls import path
from .views import register
from django.contrib.auth import views as auth_views
from users import views as user_views

app_name = 'users'


urlpatterns = [
    path('register/', register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

templates/base.html
{% load i18n static recaptcha3 %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <!-- //Meta tag Keywords -->
    <title>{% block title %} {% endblock title %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- //Meta tag Keywords -->
    <!-- Custom-Files -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- Bootstrap-Core-CSS -->
    <!--/ Style-CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all">
    <!--// Style-CSS -->
    <!-- font-awesome-icons -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}" type="text/css" media="all">
    <!--// Style-CSS -->
    <!-- //font-awesome-icons -->
  <!-- /Fonts -->
    <link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700"
          rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900"
          rel="stylesheet">
    <!-- //Fonts -->

    {% recaptcha_init %}
    {% recaptcha_ready action_name='homepage'  %}
</head>
<body>
<div id="page" class="page"><!-- mian-content -->
  <div class="main-banner bg {% block header %} {% endblock header %}" id="home">
      {% include 'include/header.html' %}
  </div>

    {% if user.is_authenticated %}
      <a class="nav-item nav-link" href="{% url 'users:profile' %}">Профиль</a>
      <form method="post" action="{% url 'users:logout' %}">
        {% csrf_token %}
        <!-- <button type="submit">Выход</button> -->
        <button type="submit" class="btn btn-success">Выход</button>
      </form>
    {% else %}
      <a class="nav-item nav-link" href="{% url 'users:login' %}">Вход</a>
      <a class="nav-item nav-link" href="{% url 'users:register' %}">Регистрация</a>
    {% endif %}

  <ol class="breadcrumb editContent">
              <li class="breadcrumb-item">
                  <a href="{% url 'movies:index' %}" class="editContent">Home</a>
              </li>
              <li class="breadcrumb-item active editContent">Single Page</li>
  </ol>
  {% if messages %}
        	{% for message in messages %}
          	<div class="alert alert-{{ message.tags }}">
            	{{ message }}
          	</div>
        	{% endfor %}
  {% endif %}
  {% block content %} 


  {% endblock content %}
  
  {% include 'include/footer.html' %}
</div>

<script src="{% static 'js/script.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="http://twitter.github.com/hogan.js/builds/3.0.1/hogan-3.0.1.js"></script>
</body>
</html>